### PR TITLE
Allow to change default field for access_token and refresh_token.

### PR DESCRIPTION
**Pull request by kamote**

### CODE REVIEW

**Comment by ghaiklor** [comment]
@drudge I've merged this, so you can publish patch release.

**Comment by drudge** [comment]
Published to npm as version `2.2.0`.

**Comment by drudge** [comment]
@ghaiklor FYI, I added you as owner to npm so you can deploy patches if you'd like.

**Comment by ghaiklor** [comment]
@drudge great, thanks. BTW, I'd done a lot other passport strategies for social networks like this one. If you notice some wrong, just let me know and I'll add you to contributors and collaborators immediately, so you can patch smth.

**Pull request merged**
